name: FairFood
description: Fair Food, just like it used to be
version: 1.0.0
main: net.snofox.minecraft.fairfood.FairFood
author: SnoFox
website: https://www.snofox.net/
api-version: 1.13
depend: []
softdepend: []